apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiod
spec:
  profile: ambient
  revision: 1-18-1
  # You may override parts of meshconfig by uncommenting the following lines.
  meshConfig:
    defaultConfig:
      proxyMetadata:
        ISTIO_META_ENABLE_HBONE: "true"
    # Telemetry API is used with ambient instead of EnvoyFilters
    defaultProviders:
      metrics:
      - prometheus
    extensionProviders:
    - name: prometheus
      prometheus: {}

  components:
    base:
      enabled: true
    pilot:
      enabled: true
      k8s:
        nodeSelector:
          istio.io/rev: 1-18-1
    cni:
      enabled: false
    ztunnel:
      enabled: false
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false

  values:
    # disable auto-injection of init containers
    istio_cni:
      enabled: true
    revisionTags:
    - canary
    pilot:
      env:
        # Setup more secure default that is off in 'default' only for backwards compatibility
        VERIFY_CERTIFICATE_AT_CLIENT: "true"
        ENABLE_AUTO_SNI: "true"

        PILOT_ENABLE_HBONE: "true"
        CA_TRUSTED_NODE_ACCOUNTS: "istio-system/ztunnel,kube-system/ztunnel"
        PILOT_ENABLE_AMBIENT_CONTROLLERS: "true"

      # TODO: https://github.com/istio/istio/issues/43243
      # variant: distroless
    telemetry:
      # Telemetry handled with Telemetry API only
      enabled: false
      v2:
        enabled: false
