apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: ztunnel
spec:
  revision: 1-18-1
  profile: ambient
  components:
    base:
      enabled: false
    pilot:
      enabled: false
    cni:
      enabled: false
    ztunnel:
      enabled: true
      k8s:
        nodeSelector:
          istio.io/rev: 1-18-1
        overlays:
          - kind: DaemonSet
            name: ztunnel
            patches:
              # Add canary release information to resources
              - path: metadata.name
                value: ztunnel-1-18-1
    ingressGateways:
    - name: istio-ingressgateway
      enabled: false
  values:
    ztunnel:
      env:
        # Add revision suffix to istiod address
        XDS_ADDRESS: https://istiod-1-18-1.istio-system.svc:15012
        CA_ADDRESS: https://istiod-1-18-1.istio-system.svc:15012
